Add header and small code tweaks

diff --git a/duration b/duration
--- a/duration
+++ b/duration
@@ -1,13 +1,26 @@
 #!/bin/bash
+#
+# duration - Print duration for the given media file(s)
 
-for FILE in "$@"
+declare    DURATION
+declare -a REQUIRES=(mediainfo)
+
+for CMD in "${REQUIRES[@]}"
+do
+    command -v "$CMD" > /dev/null ||
+    {
+        echo "Missing required command: ${CMD}" >&2
+        exit 1
+    }
+done
+
+for FILE in "${@}"
 do
     [ -f "$FILE" ] &&
     DURATION=$( mediainfo "$FILE" | \
                 grep -e "Duration" --max-count=1 | \
                 cut -f 1 -d ":" --complement | \
                 sed "s/^ //g" )
-    [ "$DURATION" ] &&
-    echo -e "\e[01;35m$( basename "$FILE" )\e[0m - $DURATION" &&
-    unset DURATION
+    [[ $DURATION ]] &&
+    echo -e "\e[01;35m$( basename "$FILE" )\e[0m - $DURATION"
 done
diff --git a/open-in-default-terminal b/open-in-default-terminal
--- a/open-in-default-terminal
+++ b/open-in-default-terminal
@@ -1,4 +1,19 @@
 #!/bin/bash
+#
+# open-in-default-terminal - Open a command using the default terminal
+
+declare -a REQUIRES=(gsettings)
+declare    TERM_EXEC
+declare    TERM_EXEC_ARG
+
+for CMD in "${REQUIRES[@]}"
+do
+    command -v "$CMD" > /dev/null ||
+    {
+        echo "Missing required command: ${CMD}" >&2
+        exit 1
+    }
+done
 
 TERM_EXEC=$(gsettings get org.gnome.desktop.default-applications.terminal exec | tr -d \')
 TERM_EXEC_ARG=$(gsettings get org.gnome.desktop.default-applications.terminal exec-arg | tr -d \')
diff --git a/pdfcount b/pdfcount
--- a/pdfcount
+++ b/pdfcount
@@ -1,13 +1,29 @@
 #!/bin/bash
+#
+# pdfcount - Count the total lines in one or more PDF files
+
+declare -i PAGES
+declare -r REQUIRES=(file pdfinfo)
+declare -i TOTAL
+
+for CMD in "${REQUIRES[@]}"
+do
+    command -v "$CMD" > /dev/null ||
+    {
+        echo "Missing required command: ${CMD}" >&2
+        exit 1
+    }
+done
 
 for FILE in "${@}"
 do
+    [[ $(file --mime-type "$FILE" | cut -f2- -d/) == "pdf" ]] || continue
     PAGES=$( pdfinfo "$FILE" 2> /dev/null | grep "^Pages:" | sed "s/[^0-9]*//" )
-    [[ $PAGES ]] &&
+    (( PAGES > 0 )) &&
     {
         echo -e "\e[01;35m$FILE\e[0m - $PAGES page(s)"
-        TOTAL=$((TOTAL + PAGES))
+        ((TOTAL += PAGES))
     }
 done
-[[ $TOTAL -gt $PAGES ]] &&
+(( TOTAL > $PAGES )) &&
 echo "$TOTAL total pages."
diff --git a/update-pot-references b/update-pot-references
--- a/update-pot-references
+++ b/update-pot-references
@@ -1,23 +1,34 @@
 #!/bin/sh
+#
+# update-pot-references - Update references for a POT file
 
-if [[ $# -lt 2 ]]
+if (($# < 2))
 then
     echo "USAGE: $(basename "$0") POT_FILE SRC_FILE [SRC_FILE...]"
     exit 1
 fi
 
-file="$1"
+for FILE in "${@}"
+do
+    [[ -f "$FILE" ]] ||
+    {
+        echo "File not found: ${FILE}"
+        exit 2
+    }
+done
+
+INPUT_FILE="$1"
 shift
 
-for line in $(grep -n -e '^msgid ' "$file" | cut -f1 -d:)
+for LINE in $(grep -n -e '^msgid ' "$INPUT_FILE" | cut -f1 -d:)
 do
-    [[ $(sed -n $((line - 1))p "$file") =~ ^"#: " ]] || continue
-    MSGID=$(sed -n ${line}p "$file" | cut -f1 -d\  --complement)
+    [[ $(sed -n $((LINE - 1))p "$INPUT_FILE") =~ ^"#: " ]] || continue
+    MSGID=$(sed -n ${LINE}p "$INPUT_FILE" | cut -f1 -d\  --complement)
     REFERENCES=$(grep -Hn "\$${MSGID}" ${@} | cut -f1,2 -d: | tr '\n' ' ')
     [[ -z $REFERENCES ]] &&
     {
-        echo "WARNING: No reference found for line ${line}: $MSGID"
+        echo "WARNING: No reference found for line ${LINE}: $MSGID"
         continue
     }
-    sed -i "$((line - 1))s~.*~#: ${REFERENCES}~" "$file"
+    sed -i "$((LINE - 1))s~.*~#: ${REFERENCES}~" "$INPUT_FILE"
 done
